// (c) 2020 Sally Faubion 
// http://www.sallysnumbers.com

var meaning = {

	destiny: {
		title: 'Destiny',
		description: 'This is the most influential number in relation to your personal motivations, what and who you like in your surroundings, and the career(s) you would be most likely to aspire toward.',
		func: 'Month + Day + Year',
		1: 'The path of the risk-taker, the entrepreneur, the wholly independent trail-blazer.',
		2: 'The path of the homemaker, the team player, the caretaker, and the collector.',
		3: 'The path of the adventurous, creative, proverbial "Peter Pan", and/or the disciplined scientific "Dapper Dan/Danielle".',
		4: 'The path of the hard-working, dedicated, forthright employee/entrepreneur and kind-hearted, loyal friend.',
		5: 'The path of the energized freedom fighter, promoter, and the stylish, socially adept/world traveler.',
		6: 'The path of the good citizen, patient teacher, champion of fairness and justice, and cosmic parent to all.',
		7: 'The path of the scholar, the perfectionist, the genius, and the keeper of secrets.',
		8: 'The path of the matriarch/patriarch, the judge, the producer/director, the orchestrator, and the class act.',
		9: 'The path of the aristocratic and genteel "old soul", and the universal humanitarian.',
		11: 'The path of the intuitive advisor/counselor, the peace-maker, and the enlightened public figure.',
		22: 'The path of the enlightened, prudent, organized, determined, and inspiring visionary.',
	},

	personality: {
		title: 'Personality',
		description: 'This number describes the behind-the-scenes or private you.',
		func: 'Day',
		1: 'You are dynamic, strong-willed and a natural leader, and your single-minded focus sets the stage for our success.',
		2: 'You are a peacemaker, nurturing, caring and kind, and an indispensable friend, mate, employee or boss.',
		3: 'You are awesomely creative, imaginary and entertaining, a superlative host or hostess.',
		4: 'You are a dedicated, detail-oriented and tireless worker, and your word is as good as gold.',
		5: 'Your intelligent, enthusiastic, and genial nature inspires and motivates all who know you.',
		6: 'You are responsible, people oriented, and a lover of beauty, nature and the home.',
		7: 'You are analytical, research-oriented, and your quest for knowledge is vast and unquenchable.',
		8: 'You are an ambitious, organized-quality operator, and born to be a leader with a penchant for protocol.',
		9: 'You are multi-talented, creative and competent and you are in your true character when being of service to others.',
		10: 'You are independent, considerate, and responsible with a take-charge nature; and a natural optimist.',
		11: 'You are sensitive, intelligent, original, inspiring and a good listener and naturally assume  the "big shoulders" role for many.',
		12: 'You are charming, personable and creative and your strong determination helps you to manifest your goals.',
		13: 'You are independent, down-to-earth and forthright, and your tenacity and endurance is extraordinary.',
		14: 'You are a storehouse of energy with a steel-trap mind that constantly churns out new ideas and opinions.',
		15: 'Your independent, creative, artistic/scientific mind craves researching and analyzing a vast array of subject matter.',
		16: 'You are uniquely intellectual, analytical mind requires alone time to sort through your endless quest for knowledge.',
		17: 'You are intelligent, ambitious, courageous, and possess enough energy and vitality to run a country!',
		18: 'You are a multi-talented powerhouse of wisdom, strength, courage, and far-reaching compassion.',
		19: 'Your adventuresome nature makes you yearn for variety and change, but when inspired, you can also be tenacious and dedicated.',
		20: 'Your warm-hearted, gentle, and congenial nature is attractive to both sexes and you will collect and retain many friends in your lifetime.',
		21: 'You are good natured, optimistic, and generous. You are also most attracted to beauty, quality, and all types of entertainment.',
		22: 'You exhibit extraordinary discipline, energy, logic, and sensitivity and you have the mind of a visionary.',
		23: 'You possess a nurturing, fun-loving, freedom-oriented spirit and your intelligent, quick mind steadily churns out original ideas and plans.',
		24: 'You are charming, social, witty, and more of a lover than a fighter. Your conscientious and giving nature tends to always go "the extra mile.',
		25: 'You are witty and wise, and you wonder about everything. Your lust for knowledge is equal only to your reservoir of innate wisdom.',
		26: 'Your personality is like that of a five-star general – steadfast and in command, fond of protocol and constantly organizing the troops.',
		27: 'Like Old King Cole, you are a merry old soul, and you possess vast innate knowledge and extraordinary perceptivity.',
		28: 'You are charming, a born diplomat, and your character is that of an achiever and leader.',
		29: 'Your gentle, sensitive nature is complimented by a combination of energy and charisma that draws people to you like a magnet.',
		30: 'You are intelligent, creative, fun-loving, and blessed with a great sense of humor, and exceptionally talented when given some creative latitude.',
		31: 'You are creative, innovative, and posses a vast amount of knowledge. Conscientious, dependable and timely, you are also a creature of habit.',
	},

	attitude: {
		title: 'Attitude',
		description: 'This number is most powerful in the first 30-35 years of your life and represents the how and why you react to circumstances in your youth.',
		func: 'Month + Day',
		1: 'You are born with a strong will and independent nature. You prefer to make your own choices and are stubborn when pushed in a different direction.',
		2: 'You are born to be a sweet, gentle, kind and caring child and young adult. You love to nurture and be nurtured; also inclined to be sensitive.',
		3: 'You are born somewhat shy but once you learn to speak, you can become a natural entertainer, adventuresome, and delightful.',
		4: 'You are born with a sensitive, stubborn temperament, but can be very sweet and dutiful when given praise and encouragement.',
		5: 'You are born with energy abounding! You need constant mental and physical stimulation and your temper flares when impatient.',
		6: 'You are born to be responsible, conscientious, considerate, kind and caring to everyone, especially your parents\', siblings, friends, and animals.',
		7: 'You are born with a brilliant mind that needs alone time to indulge your quest for knowledge and vast interests and intrigues.',
		8: 'You are born to be exemplary in everything you do; which originates from your need to feel in control. You are the "straight A student" when encouraged.',
		9: 'You are born with a more adult-like sensibility at a very early age. Praise and encouragement from those closest to you fuel your achievements.',
		11: 'You are born super sensitive; highly intuitive, high-minded and a lover of music; sweet, gentle and cerebral, when inspired you are star material.',
		22: 'You are born with a stubborn streak but that can be a very purposeful, enterprising, inspired and ingenious expression when given encouragement.',
	},

	character: {
		title: 'Character',
		description: 'This number represents primarily your public and social qualities, but you would also exhibit much of the same in your personal relations, too.',
		func: 'Letters',
		1: 'Possessing an original and innovative mind, with a steadfast focus on your goals qualifies you as a leader',
		2: 'Being naturally diplomatic, good-natured and a peacemaker, your pubic persona is like that of an ambassador for the people.',
		3: 'Your naturally optimistic, enthusiastic, and creative communication.skills qualify you as an entertaining, eloquent and inspiring speaker/leader.',
		4: 'Your conscientious, organized, systematic and reliable public persona makes you a sought-after worker-bee or Chairman of the Board.',
		5: 'Your charming, articulate, flexible and style-conscious nature make you a trendsetter who can engage and inspire many when focused on a mission',
		6: 'As a born humanitarian, community-oriented, outstanding parent/teacher/human who always "goes the extra mile" you are an exemplary committee or cause leader.',
		7: 'As a philosophically avant-garde, knowledge-seeking genius, you don\'t seek the limelight but are superlative teachers, professors, and career specialists.',
		8: 'Your commanding, exemplary teacher-of-teachers, judge/jury, producer/director persona possesses a sixth sense that enables you to readily distinguish right from wrong.',
		9: 'As a born sage, aristocratic, socially pleasing humanitarian, you gravitate toward the community that can benefit most; from  "selfless server" mission.',
		11: 'As an empathetic, enlightened and understanding counselor or community leader, you belong in the limelight; the 11 is known as the sign of illumination.',
		22: 'As a high-minded builder of empires and spiritually-oriented organizer, you are best suited to help pubic causes and companies that appreciate your straightforward style.',
	},

	soul: {
		title: 'Soul Urge',
		description: 'This influence tenders a view of your intuitive, soulful self.',
		func: 'Vowels',
		1: 'Your Soul\'s Urge is to Innovative, creative, and lead the masses to a higher realm of consciousness and understanding that engenders compassion for all.',
		2: 'Your Soul\'s Urge is to effect peace, harmony, finesse to bring about greater nurturing and loving qualities in those you know and comfort.',
		3: 'Your Soul\'s Urge is to bring JOY, enthusiasm, passion, and arouse the imagination of others with creativity and heart-warming concepts and interests.',
		4: 'Your Soul\'s Urge is to deliver honesty, dependability, practicality, and determination to help others and yourself achieve inspiring and enlightening outcomes',
		5: 'Your Soul\'s Urge is to use your abounding energy, broad-mindedness and progressive mental attributes to help bring forth high-minded contributions to mankind.',
		6: 'Your Soul\'s Urge is to be responsible, conscientious, caring and kind to one and all, and to teach, counsel, and comfort to attain those qualities, too.',
		7: 'Your Soul\'s Urge is to use your analytical, research-oriented and questioning nature to discover or uncover something meaningful that will help the many, as opposed to a few.',
		8: 'Your Soul\'s Urge is to bring quality, consistency and inspiration to others and to effect your natural finesse, and quality in you all touch.',
		9: 'Your Soul\s Urge is to use your aristocratic, gentile and humaine qualities with consistency which will help to set the stage for others to emulate.',
		11: 'Your Soul\'s Urge is to bring peace, harmony, beauty and honorability as an example of your highest spiritual qualities for all to appreciate and perhaps imitate.',
		22: 'Your Soul\'s Urge is that of a "Master Builder," one whose soulful desire is to help and serve mankind and the earth with high-mindedness and humanitarianism.',
	},

	agenda: {
		title: 'Hidden Agenda',
		description: 'This vibration offers your innate (hidden) desires.',
		func: 'Consonants',
		1: 'This agenda incites an innate desire to be independent, to lead, to innovate, and to create original and unique concepts and things.',
		2: 'This agenda brings forth the innate " desire" to live life in peace and harmony, effecting a non-aggressive, cooperative and congenial nature.',
		3: 'This agenda inspires an innate desire to be more creative, entertaining, and to travel the world. Pleasure and freedom are high priorities for this agenda.',
		4: 'This agenda entails logic, organization, and perseverance to manifest the innate needs, desires and peace of mind you harbor and hold.',
		5: 'This agenda inspires an innate desire for freedom more than anything else, along with acquiring the ability to travel and live unrestrained as much as possible.',
		6: 'This agenda has a strong innate humanitarianism focus – helping and caring for all things of the earth – humans, animals and the beautiful earth itself.',
		7: 'This agenda provokes an innate thirst for gaining knowledge associated with the sciences (esoteric or otherwise), philosophies, arts, and spirituality.',
		8: 'This agenda expresses an innate desire for power, acclaim and amassing huge amounts of money, or being an enlightened teacher of the masses',
		9: 'This agenda affects an innate desire to attain the finest of everything from clothing and cars to entertainment, or an inordinate need to live a wholly humanitarian life without a thought for self.',
		11: 'This agenda incites an innate need to minister, counsel, or participate in the healing arts in a way that helps the many, or to become known for your humanitarian services.',
		22: 'This agenda inspires an innate desire to do something grand for mankind. This Master Number gives you the ability to scale the highest mountains or innovate an exemplary product or philosophy',
	},

	purpose: {
		title: 'Divine Purpose',
		description: 'This is your farewell-performance number vibration. It is what your Soulful Self has chosen to achieve in your latter years of life.',
		func: 'Destiny + Character',
		1: 'Your Divine Purpose is to leave behind a legacy of something you pioneered - a concept, a product, a foundation.',
		2: 'Your Divine Purpose is to bring comfort and harmony to your fellow humans.',
		3: 'Your Divine Purpose is to use your creative and imaginative talents to produce a product, an idea, a book, a film, or some other form of artful expression.',
		4: 'Your Divine Purpose is to build a stable foundation that helps people and has a humanitarian focus.',
		5: 'Your Divine Purpose is to help to effect progressive changes that make life better for future generations.',
		6: 'Your Divine Purpose is to teach, to instigate, and to help humanitarian causes, to care for home and family, and be socially responsible.',
		7: 'Your Divine Purpose is to impart the vast knowledge you have gathered in a science, an art, a philosophy, or a religion through a creative endeavor.',
		8: 'Your Divine Purpose is to lead, direct, initiate, and instigate as a leader or executive, and to help the less fortunate through philanthropy.',
		9: 'Your Divine Purpose is to be a universal humanitarian - a good parent, a good mate, and a good citizen; a philanthropist, a minister, a politician - working for the betterment of mankind.',
		11: 'Your Divine Purpose is to help people on the spiritual, psychological, and mental planes. To uplift others with words of wisdom; to listen, offer advice, and help others to move forward on their life\'s journey.',
		22: 'Your Divine Purpose is to organize and build; to maintain a business enterprise that offers work to others and helps people through service to the community and perhaps the world.',
	},

}
